# Device config variables
ANDROID_VERSION_LOCAL_1 = '15'
DEVICE_NAME_LOCAL_1 = 'Medium_Phone_API_35'

# Mock server config variables
CONFIG_MOCK_SERVER_PATH = ''
CONFIG_MOCK_SERVER_DOMAIN = '10.0.2.2'
CONFIG_MOCK_SERVER_PORT = '3000'